# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
